"use client";

import { RecordItem } from "@/types/transactions";
import { useState } from "react";

type Props = {
  onAdd: (row: RecordItem) => void;
};

const initialRow: RecordItem = {
  id: "", // will be generated by backend
  date: new Date().toISOString().slice(0, 10),
  merchant_name: "",
  transaction_description: "",
  main_category: "",
  sub_category: "",
  detailed_category: "",
  amount_rm: 0,
};

export default function NewTransactionRow({ onAdd }: Props) {
  const [newRow, setNewRow] = useState<RecordItem>(initialRow);

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>
  ) => {
    setNewRow({ ...newRow, [e.target.name]: e.target.value });
  };

  const handleSubmit = () => {
    onAdd(newRow); // send row (with empty id)
    setNewRow(initialRow); // reset fields
  };

  return (
    <tr className="border-t border-velqen-gray bg-velqen-dark text-white">
      <td className="px-3 py-4">
        <input
          name="date"
          type="date"
          value={newRow.date}
          onChange={handleChange}
          className="border rounded px-2 py-1 w-full bg-velqen-gray"
        />
      </td>
      <td className="px-3 py-4">
        <input
          name="merchant_name"
          value={newRow.merchant_name}
          onChange={handleChange}
          className="border rounded px-2 py-1 w-full bg-velqen-gray"
        />
      </td>
      <td className="px-3 py-4">
        <input
          name="transaction_description"
          value={newRow.transaction_description}
          onChange={handleChange}
          className="border rounded px-2 py-1 w-full bg-velqen-gray"
        />
      </td>
      <td className="px-3 py-4">
        <input
          name="main_category"
          value={newRow.main_category}
          onChange={handleChange}
          className="border rounded px-2 py-1 w-full bg-velqen-gray"
        />
      </td>
      <td className="px-3 py-4">
        <input
          name="sub_category"
          value={newRow.sub_category}
          onChange={handleChange}
          className="border rounded px-2 py-1 w-full bg-velqen-gray"
        />
      </td>
      <td className="px-3 py-4">
        <input
          name="detailed_category"
          value={newRow.detailed_category}
          onChange={handleChange}
          className="border rounded px-2 py-1 w-full bg-velqen-gray"
        />
      </td>
      <td className="px-3 py-4 text-right">
        <input
          name="amount_rm"
          type="number"
          value={newRow.amount_rm}
          onChange={handleChange}
          className="border rounded px-2 py-1 w-24 text-right bg-velqen-gray"
        />
      </td>
      <td className="px-3 py-4 text-center">
        <button
          onClick={handleSubmit}
          className="px-3 py-1 bg-green-600 text-white rounded hover:bg-green-700"
        >
          Add
        </button>
      </td>
    </tr>
  );
}
